// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/Payment.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include "libconfparser/confparser.hpp"
#include "BossMonitorClient.hh"
#include "Payment.hh"
#include "log4z/log4z.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::PaymentInterface;

using namespace zsummer::log4z;

class PaymentHandler : virtual public PaymentIf {
    public:
        PaymentHandler(LoggerId logId) {
            // Your initialization goes here
            m_logId = logId;
            m_payment=new Payment(m_logId);
        }

        ~PaymentHandler() {
            // Your initialization goes here
            delete m_payment;
            m_payment=NULL;
        }

        bool subscribe(const  ::BossData::Payment& data) {
            // Your implementation goes here
            LOG_INFO(m_logId, "Receive a message...");
            LOG_INFO(m_logId, "Pay "<<data.fee<<" to "<<data.nbr);
            PaymentData my_data;
            my_data.nbr = data.nbr;
            my_data.fee= data.fee;
            m_payment->doBiz(my_data);
            LOG_INFO(m_logId, "Server handle successfully.");

            return true;
        }

    private:
        Payment *m_payment;
        LoggerId m_logId;

};

void mkDaemon(void)
{
    pid_t pid;
    pid_t sid;

    pid = fork();
    if (pid == -1)
      printf("Failed to fork() ");

    if (pid) {
        exit(0);
    }

    sid = setsid();
    if (sid == -1)
      abort();
    return;
} 

int main(int argc, char **argv) {

    mkDaemon();

    LoggerId logId;
    ILog4zManager::GetInstance()->Config("../conf/log.cfg");
    logId = ILog4zManager::GetInstance()->FindLogger("Payment");
    ILog4zManager::GetInstance()->Start();

    LOG_INFO(logId, "Parse boss.cfg");
    CONF_PARSER_SIMPLE_INIT("../conf/boss.cfg");
    int port = CONF_PARSER_GET_NUM_VAL("Payment", "port");
    LOG_INFO(logId, "Server listening port:"<<port);

    shared_ptr<PaymentHandler> handler(new PaymentHandler(logId));
    shared_ptr<TProcessor> processor(new PaymentProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    ::BossMonitorClient client;
    BossData::BossMonitor data;
    data.id=getpid();
    data.name=basename(argv[0]);
    data.status="Active";
    data.ip=CONF_PARSER_GET_VAL("Payment", "ip");;
    data.port=port;
    client.subscribe(data);

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
    return 0;
}

