// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/AdjustAcctItem.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PosixThreadFactory.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/server/TThreadedServer.h>
#include "BossMonitorClient.hh"
#include "AdjustAcctItem.hh"
#include "log4z/log4z.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::concurrency;

using boost::shared_ptr;

using namespace  ::BossInterface;

using namespace zsummer::log4z;

class AdjustAcctItemHandler : virtual public AdjustAcctItemIf {
    public:
        AdjustAcctItemHandler(LoggerId logId) {
            // Your initialization goes here
            m_logId = logId;
            m_adjust_acct_item=new AdjustAcctItem(m_logId);
        }

        ~AdjustAcctItemHandler() {
            // Your initialization goes here
            delete m_adjust_acct_item;
            m_adjust_acct_item=NULL;
        }

        bool send(const  ::BossData::AdjustAcctItem& data) {
            // Your implementation goes here
            LOG_INFO(m_logId, "Receive a message...");
            LOG_INFO(m_logId, "Add acct item for "<<data.nbr<<" Fee: "<<data.fee<<" YM: "<<data.ym);
            AdjustAcctItemData my_data;
            my_data.nbr = data.nbr;
            my_data.fee= data.fee;
            my_data.ym = data.ym;
            m_adjust_acct_item->doBiz(my_data);
            LOG_INFO(m_logId, "Server handle successfully.");

            return true;
        }

    private:
        AdjustAcctItem *m_adjust_acct_item;
        LoggerId m_logId;

};

void mkDaemon(void)
{
    pid_t pid;
    pid_t sid;

    pid = fork();
    if (pid == -1)
      printf("Failed to fork() ");

    if (pid) {
        exit(0);
    }

    sid = setsid();
    if (sid == -1)
      abort();
    return;
} 

int main(int argc, char **argv) {
    mkDaemon();

    LoggerId logId;
    ILog4zManager::GetInstance()->Config("../conf/log.cfg");
    logId = ILog4zManager::GetInstance()->FindLogger("AdjustAcctItem");
    ILog4zManager::GetInstance()->Start();

    LOG_INFO(logId, "Parse boss.cfg");
    CONF_PARSER_SIMPLE_INIT("../conf/boss.cfg");
    int port = CONF_PARSER_GET_NUM_VAL("AdjustAcctItem", "port");
    LOG_INFO(logId, "Server listening port:"<<port);

    shared_ptr<AdjustAcctItemHandler> handler(new AdjustAcctItemHandler(logId));
    shared_ptr<TProcessor> processor(new AdjustAcctItemProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    ::BossMonitorClient client;
    BossData::BossMonitor data;
    data.id=getpid();
    data.name=basename(argv[0]);
    data.status="Active";
    data.ip=CONF_PARSER_GET_VAL("AdjustAcctItem", "ip");;
    data.port=port;
    client.subscribe(data);

    shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(10);
    shared_ptr<PosixThreadFactory> threadFactory = shared_ptr<PosixThreadFactory>(new PosixThreadFactory());

    threadManager->threadFactory(threadFactory);
    threadManager->start();

    TThreadPoolServer server(processor, serverTransport, transportFactory, protocolFactory, threadManager);
    server.serve();
    return 0;
}

