/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AdjustAcctItem_CONSTANTS_H
#define AdjustAcctItem_CONSTANTS_H

#include "AdjustAcctItem_types.h"

namespace BossInterface {

class AdjustAcctItemConstants {
 public:
  AdjustAcctItemConstants();

};

extern const AdjustAcctItemConstants g_AdjustAcctItem_constants;

} // namespace

#endif
