/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BossMonitor_constants.h"

namespace BossInterface {

const BossMonitorConstants g_BossMonitor_constants;

BossMonitorConstants::BossMonitorConstants() {
}

} // namespace

