/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BossData_CONSTANTS_H
#define BossData_CONSTANTS_H

#include "BossData_types.h"

namespace BossData {

class BossDataConstants {
 public:
  BossDataConstants();

};

extern const BossDataConstants g_BossData_constants;

} // namespace

#endif
