// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FetchBalance.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::BossInterface;

class FetchBalanceHandler : virtual public FetchBalanceIf {
 public:
  FetchBalanceHandler() {
    // Your initialization goes here
  }

  double fetchBalance(const std::string& nbr) {
    // Your implementation goes here
    printf("fetchBalance\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FetchBalanceHandler> handler(new FetchBalanceHandler());
  shared_ptr<TProcessor> processor(new FetchBalanceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

