/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FetchNbr_constants.h"

namespace BossInterface {

const FetchNbrConstants g_FetchNbr_constants;

FetchNbrConstants::FetchNbrConstants() {
}

} // namespace

