/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FetchNbr_CONSTANTS_H
#define FetchNbr_CONSTANTS_H

#include "FetchNbr_types.h"

namespace BossInterface {

class FetchNbrConstants {
 public:
  FetchNbrConstants();

};

extern const FetchNbrConstants g_FetchNbr_constants;

} // namespace

#endif
