/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OpenAccountServlet_H
#define OpenAccountServlet_H

#include <thrift/TDispatchProcessor.h>
#include "OpenAccount_types.h"

namespace BossInterface {

class OpenAccountServletIf {
 public:
  virtual ~OpenAccountServletIf() {}
  virtual bool send(const  ::BossData::OpenAccount& data) = 0;
};

class OpenAccountServletIfFactory {
 public:
  typedef OpenAccountServletIf Handler;

  virtual ~OpenAccountServletIfFactory() {}

  virtual OpenAccountServletIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(OpenAccountServletIf* /* handler */) = 0;
};

class OpenAccountServletIfSingletonFactory : virtual public OpenAccountServletIfFactory {
 public:
  OpenAccountServletIfSingletonFactory(const boost::shared_ptr<OpenAccountServletIf>& iface) : iface_(iface) {}
  virtual ~OpenAccountServletIfSingletonFactory() {}

  virtual OpenAccountServletIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(OpenAccountServletIf* /* handler */) {}

 protected:
  boost::shared_ptr<OpenAccountServletIf> iface_;
};

class OpenAccountServletNull : virtual public OpenAccountServletIf {
 public:
  virtual ~OpenAccountServletNull() {}
  bool send(const  ::BossData::OpenAccount& /* data */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _OpenAccountServlet_send_args__isset {
  _OpenAccountServlet_send_args__isset() : data(false) {}
  bool data;
} _OpenAccountServlet_send_args__isset;

class OpenAccountServlet_send_args {
 public:

  OpenAccountServlet_send_args() {
  }

  virtual ~OpenAccountServlet_send_args() throw() {}

   ::BossData::OpenAccount data;

  _OpenAccountServlet_send_args__isset __isset;

  void __set_data(const  ::BossData::OpenAccount& val) {
    data = val;
  }

  bool operator == (const OpenAccountServlet_send_args & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const OpenAccountServlet_send_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenAccountServlet_send_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenAccountServlet_send_pargs {
 public:


  virtual ~OpenAccountServlet_send_pargs() throw() {}

  const  ::BossData::OpenAccount* data;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenAccountServlet_send_result__isset {
  _OpenAccountServlet_send_result__isset() : success(false) {}
  bool success;
} _OpenAccountServlet_send_result__isset;

class OpenAccountServlet_send_result {
 public:

  OpenAccountServlet_send_result() : success(0) {
  }

  virtual ~OpenAccountServlet_send_result() throw() {}

  bool success;

  _OpenAccountServlet_send_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const OpenAccountServlet_send_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenAccountServlet_send_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenAccountServlet_send_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenAccountServlet_send_presult__isset {
  _OpenAccountServlet_send_presult__isset() : success(false) {}
  bool success;
} _OpenAccountServlet_send_presult__isset;

class OpenAccountServlet_send_presult {
 public:


  virtual ~OpenAccountServlet_send_presult() throw() {}

  bool* success;

  _OpenAccountServlet_send_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class OpenAccountServletClient : virtual public OpenAccountServletIf {
 public:
  OpenAccountServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  OpenAccountServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool send(const  ::BossData::OpenAccount& data);
  void send_send(const  ::BossData::OpenAccount& data);
  bool recv_send();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class OpenAccountServletProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<OpenAccountServletIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (OpenAccountServletProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_send(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  OpenAccountServletProcessor(boost::shared_ptr<OpenAccountServletIf> iface) :
    iface_(iface) {
    processMap_["send"] = &OpenAccountServletProcessor::process_send;
  }

  virtual ~OpenAccountServletProcessor() {}
};

class OpenAccountServletProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  OpenAccountServletProcessorFactory(const ::boost::shared_ptr< OpenAccountServletIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< OpenAccountServletIfFactory > handlerFactory_;
};

class OpenAccountServletMultiface : virtual public OpenAccountServletIf {
 public:
  OpenAccountServletMultiface(std::vector<boost::shared_ptr<OpenAccountServletIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~OpenAccountServletMultiface() {}
 protected:
  std::vector<boost::shared_ptr<OpenAccountServletIf> > ifaces_;
  OpenAccountServletMultiface() {}
  void add(boost::shared_ptr<OpenAccountServletIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool send(const  ::BossData::OpenAccount& data) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->send(data);
    }
    return ifaces_[i]->send(data);
  }

};

} // namespace

#endif
