/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PayFee_constants.h"

namespace BossInterface {

const PayFeeConstants g_PayFee_constants;

PayFeeConstants::PayFeeConstants() {
}

} // namespace

