/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PayFee_CONSTANTS_H
#define PayFee_CONSTANTS_H

#include "PayFee_types.h"

namespace BossInterface {

class PayFeeConstants {
 public:
  PayFeeConstants();

};

extern const PayFeeConstants g_PayFee_constants;

} // namespace

#endif
