/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PayFee_H
#define PayFee_H

#include <thrift/TDispatchProcessor.h>
#include "PayFee_types.h"

namespace BossInterface {

class PayFeeIf {
 public:
  virtual ~PayFeeIf() {}
  virtual bool subscribe(const  ::BossData::PayFee& datas) = 0;
};

class PayFeeIfFactory {
 public:
  typedef PayFeeIf Handler;

  virtual ~PayFeeIfFactory() {}

  virtual PayFeeIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PayFeeIf* /* handler */) = 0;
};

class PayFeeIfSingletonFactory : virtual public PayFeeIfFactory {
 public:
  PayFeeIfSingletonFactory(const boost::shared_ptr<PayFeeIf>& iface) : iface_(iface) {}
  virtual ~PayFeeIfSingletonFactory() {}

  virtual PayFeeIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PayFeeIf* /* handler */) {}

 protected:
  boost::shared_ptr<PayFeeIf> iface_;
};

class PayFeeNull : virtual public PayFeeIf {
 public:
  virtual ~PayFeeNull() {}
  bool subscribe(const  ::BossData::PayFee& /* datas */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _PayFee_subscribe_args__isset {
  _PayFee_subscribe_args__isset() : datas(false) {}
  bool datas;
} _PayFee_subscribe_args__isset;

class PayFee_subscribe_args {
 public:

  PayFee_subscribe_args() {
  }

  virtual ~PayFee_subscribe_args() throw() {}

   ::BossData::PayFee datas;

  _PayFee_subscribe_args__isset __isset;

  void __set_datas(const  ::BossData::PayFee& val) {
    datas = val;
  }

  bool operator == (const PayFee_subscribe_args & rhs) const
  {
    if (!(datas == rhs.datas))
      return false;
    return true;
  }
  bool operator != (const PayFee_subscribe_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PayFee_subscribe_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PayFee_subscribe_pargs {
 public:


  virtual ~PayFee_subscribe_pargs() throw() {}

  const  ::BossData::PayFee* datas;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PayFee_subscribe_result__isset {
  _PayFee_subscribe_result__isset() : success(false) {}
  bool success;
} _PayFee_subscribe_result__isset;

class PayFee_subscribe_result {
 public:

  PayFee_subscribe_result() : success(0) {
  }

  virtual ~PayFee_subscribe_result() throw() {}

  bool success;

  _PayFee_subscribe_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const PayFee_subscribe_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PayFee_subscribe_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PayFee_subscribe_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PayFee_subscribe_presult__isset {
  _PayFee_subscribe_presult__isset() : success(false) {}
  bool success;
} _PayFee_subscribe_presult__isset;

class PayFee_subscribe_presult {
 public:


  virtual ~PayFee_subscribe_presult() throw() {}

  bool* success;

  _PayFee_subscribe_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PayFeeClient : virtual public PayFeeIf {
 public:
  PayFeeClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  PayFeeClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool subscribe(const  ::BossData::PayFee& datas);
  void send_subscribe(const  ::BossData::PayFee& datas);
  bool recv_subscribe();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PayFeeProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<PayFeeIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PayFeeProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_subscribe(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PayFeeProcessor(boost::shared_ptr<PayFeeIf> iface) :
    iface_(iface) {
    processMap_["subscribe"] = &PayFeeProcessor::process_subscribe;
  }

  virtual ~PayFeeProcessor() {}
};

class PayFeeProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PayFeeProcessorFactory(const ::boost::shared_ptr< PayFeeIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< PayFeeIfFactory > handlerFactory_;
};

class PayFeeMultiface : virtual public PayFeeIf {
 public:
  PayFeeMultiface(std::vector<boost::shared_ptr<PayFeeIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PayFeeMultiface() {}
 protected:
  std::vector<boost::shared_ptr<PayFeeIf> > ifaces_;
  PayFeeMultiface() {}
  void add(boost::shared_ptr<PayFeeIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool subscribe(const  ::BossData::PayFee& datas) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->subscribe(datas);
    }
    return ifaces_[i]->subscribe(datas);
  }

};

} // namespace

#endif
