/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Payment_CONSTANTS_H
#define Payment_CONSTANTS_H

#include "Payment_types.h"

namespace BossInterface {

class PaymentConstants {
 public:
  PaymentConstants();

};

extern const PaymentConstants g_Payment_constants;

} // namespace

#endif
