/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BossMonitor_CONSTANTS_H
#define BossMonitor_CONSTANTS_H

#include "BossMonitor_types.h"

namespace BossInterface {

class BossMonitorConstants {
 public:
  BossMonitorConstants();

};

extern const BossMonitorConstants g_BossMonitor_constants;

} // namespace

#endif
