/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BossData_constants.h"

namespace BossData {

const BossDataConstants g_BossData_constants;

BossDataConstants::BossDataConstants() {
}

} // namespace

