/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OpenAccount_CONSTANTS_H
#define OpenAccount_CONSTANTS_H

#include "OpenAccount_types.h"

namespace BossInterface {

class OpenAccountConstants {
 public:
  OpenAccountConstants();

};

extern const OpenAccountConstants g_OpenAccount_constants;

} // namespace

#endif
