/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OpenAccount_constants.h"

namespace BossInterface {

const OpenAccountConstants g_OpenAccount_constants;

OpenAccountConstants::OpenAccountConstants() {
}

} // namespace

