// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "OpenAccountServlet.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::BossInterface;

class OpenAccountServletHandler : virtual public OpenAccountServletIf {
 public:
  OpenAccountServletHandler() {
    // Your initialization goes here
  }

  bool Sender(const std::vector< ::BossData::OpenAccount> & datas) {
    // Your implementation goes here
    printf("Sender\n");
  }

  void Sender2(const std::vector< ::BossData::OpenAccount> & datas) {
    // Your implementation goes here
    printf("Sender2\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<OpenAccountServletHandler> handler(new OpenAccountServletHandler());
  shared_ptr<TProcessor> processor(new OpenAccountServletProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

