/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OpenAccountServlet_H
#define OpenAccountServlet_H

#include <thrift/TDispatchProcessor.h>
#include "OpenAccount_types.h"

namespace BossInterface {

class OpenAccountServletIf {
 public:
  virtual ~OpenAccountServletIf() {}
  virtual bool Sender(const std::vector< ::BossData::OpenAccount> & datas) = 0;
  virtual void Sender2(const std::vector< ::BossData::OpenAccount> & datas) = 0;
};

class OpenAccountServletIfFactory {
 public:
  typedef OpenAccountServletIf Handler;

  virtual ~OpenAccountServletIfFactory() {}

  virtual OpenAccountServletIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(OpenAccountServletIf* /* handler */) = 0;
};

class OpenAccountServletIfSingletonFactory : virtual public OpenAccountServletIfFactory {
 public:
  OpenAccountServletIfSingletonFactory(const boost::shared_ptr<OpenAccountServletIf>& iface) : iface_(iface) {}
  virtual ~OpenAccountServletIfSingletonFactory() {}

  virtual OpenAccountServletIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(OpenAccountServletIf* /* handler */) {}

 protected:
  boost::shared_ptr<OpenAccountServletIf> iface_;
};

class OpenAccountServletNull : virtual public OpenAccountServletIf {
 public:
  virtual ~OpenAccountServletNull() {}
  bool Sender(const std::vector< ::BossData::OpenAccount> & /* datas */) {
    bool _return = false;
    return _return;
  }
  void Sender2(const std::vector< ::BossData::OpenAccount> & /* datas */) {
    return;
  }
};

typedef struct _OpenAccountServlet_Sender_args__isset {
  _OpenAccountServlet_Sender_args__isset() : datas(false) {}
  bool datas;
} _OpenAccountServlet_Sender_args__isset;

class OpenAccountServlet_Sender_args {
 public:

  OpenAccountServlet_Sender_args() {
  }

  virtual ~OpenAccountServlet_Sender_args() throw() {}

  std::vector< ::BossData::OpenAccount>  datas;

  _OpenAccountServlet_Sender_args__isset __isset;

  void __set_datas(const std::vector< ::BossData::OpenAccount> & val) {
    datas = val;
  }

  bool operator == (const OpenAccountServlet_Sender_args & rhs) const
  {
    if (!(datas == rhs.datas))
      return false;
    return true;
  }
  bool operator != (const OpenAccountServlet_Sender_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenAccountServlet_Sender_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenAccountServlet_Sender_pargs {
 public:


  virtual ~OpenAccountServlet_Sender_pargs() throw() {}

  const std::vector< ::BossData::OpenAccount> * datas;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenAccountServlet_Sender_result__isset {
  _OpenAccountServlet_Sender_result__isset() : success(false) {}
  bool success;
} _OpenAccountServlet_Sender_result__isset;

class OpenAccountServlet_Sender_result {
 public:

  OpenAccountServlet_Sender_result() : success(0) {
  }

  virtual ~OpenAccountServlet_Sender_result() throw() {}

  bool success;

  _OpenAccountServlet_Sender_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const OpenAccountServlet_Sender_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenAccountServlet_Sender_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenAccountServlet_Sender_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenAccountServlet_Sender_presult__isset {
  _OpenAccountServlet_Sender_presult__isset() : success(false) {}
  bool success;
} _OpenAccountServlet_Sender_presult__isset;

class OpenAccountServlet_Sender_presult {
 public:


  virtual ~OpenAccountServlet_Sender_presult() throw() {}

  bool* success;

  _OpenAccountServlet_Sender_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _OpenAccountServlet_Sender2_args__isset {
  _OpenAccountServlet_Sender2_args__isset() : datas(false) {}
  bool datas;
} _OpenAccountServlet_Sender2_args__isset;

class OpenAccountServlet_Sender2_args {
 public:

  OpenAccountServlet_Sender2_args() {
  }

  virtual ~OpenAccountServlet_Sender2_args() throw() {}

  std::vector< ::BossData::OpenAccount>  datas;

  _OpenAccountServlet_Sender2_args__isset __isset;

  void __set_datas(const std::vector< ::BossData::OpenAccount> & val) {
    datas = val;
  }

  bool operator == (const OpenAccountServlet_Sender2_args & rhs) const
  {
    if (!(datas == rhs.datas))
      return false;
    return true;
  }
  bool operator != (const OpenAccountServlet_Sender2_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenAccountServlet_Sender2_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenAccountServlet_Sender2_pargs {
 public:


  virtual ~OpenAccountServlet_Sender2_pargs() throw() {}

  const std::vector< ::BossData::OpenAccount> * datas;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class OpenAccountServletClient : virtual public OpenAccountServletIf {
 public:
  OpenAccountServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  OpenAccountServletClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool Sender(const std::vector< ::BossData::OpenAccount> & datas);
  void send_Sender(const std::vector< ::BossData::OpenAccount> & datas);
  bool recv_Sender();
  void Sender2(const std::vector< ::BossData::OpenAccount> & datas);
  void send_Sender2(const std::vector< ::BossData::OpenAccount> & datas);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class OpenAccountServletProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<OpenAccountServletIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (OpenAccountServletProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Sender(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Sender2(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  OpenAccountServletProcessor(boost::shared_ptr<OpenAccountServletIf> iface) :
    iface_(iface) {
    processMap_["Sender"] = &OpenAccountServletProcessor::process_Sender;
    processMap_["Sender2"] = &OpenAccountServletProcessor::process_Sender2;
  }

  virtual ~OpenAccountServletProcessor() {}
};

class OpenAccountServletProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  OpenAccountServletProcessorFactory(const ::boost::shared_ptr< OpenAccountServletIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< OpenAccountServletIfFactory > handlerFactory_;
};

class OpenAccountServletMultiface : virtual public OpenAccountServletIf {
 public:
  OpenAccountServletMultiface(std::vector<boost::shared_ptr<OpenAccountServletIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~OpenAccountServletMultiface() {}
 protected:
  std::vector<boost::shared_ptr<OpenAccountServletIf> > ifaces_;
  OpenAccountServletMultiface() {}
  void add(boost::shared_ptr<OpenAccountServletIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool Sender(const std::vector< ::BossData::OpenAccount> & datas) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Sender(datas);
    }
    return ifaces_[i]->Sender(datas);
  }

  void Sender2(const std::vector< ::BossData::OpenAccount> & datas) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Sender2(datas);
    }
    ifaces_[i]->Sender2(datas);
  }

};

} // namespace

#endif
