/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Payment_constants.h"

namespace PaymentInterface {

const PaymentConstants g_Payment_constants;

PaymentConstants::PaymentConstants() {
}

} // namespace

